#!/usr/bin/env python3

import argparse
import os
import re
import subprocess
import stat
import json
from getpass import getpass
from pick import pick

DATA_PATH = os.path.expanduser('~') + '/.wifdata'
MACADDR_RE = re.compile('([0-9a-f]{2}\:){5}([0-9a-f]){2}')

parser = argparse.ArgumentParser(description='Handle internet connections on MacOS.')
parser.add_argument('verb')
parser.add_argument('-n', dest='network', help='Name of network to which to connect')
parser.add_argument('-p', dest='password', help='Password for network to which you wish to connect. USE NOT RECOMMENDED.')
args = parser.parse_args()

networks = {}
if os.path.isfile(DATA_PATH):
    with open(DATA_PATH, 'r') as f:
        networks = json.load(f)
else:
    with open(DATA_PATH, 'w') as f:
        json.dump(networks, f)
    os.chmod(DATA_PATH, stat.S_IRUSR | stat.S_IRUSR)

# Warn if group or public can read config and the private details therein.
if os.stat(DATA_PATH).st_mode & (stat.S_IRGRP | stat.S_IROTH):
    print('Warning: network data file ({path}) may be accessible by other users.'.format(path=DATA_PATH))

class WiFi:
    def __init__(self):
        pass

    def power(self, power: bool):
        # TODO: Detect proper interface, not always en1
        os.system('/usr/sbin/networksetup -setairportpower en1 ' + ('on' if power else 'off'))

    def networks(self):
        # TODO: What a mess.
        # TODO: -s is a legacy flag and may be removed in the future.
        raw = subprocess.check_output(['/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport', '-s']).decode()
        if raw == 'No networks found\n':
            # TODO: Colors or something
            return []
        else:
            # TODO: Naming in this section especially is confusing
            # Must remove last empty item and title row
            split = [line.split() for line in raw.split('\n')][1:-1]
            networks = []
            for col in split:
                #print(network)
                name_col = 1
                ssid = col[0]
                while not MACADDR_RE.match(col[name_col]):
                    ssid += ' ' + col[name_col]
                    name_col += 1
                security = col[-1].split('(')[0]
                # TODO: Return more details, not just name and security level.
                networks.append({
                    'ssid': ssid,
                    'security': security,
                })
            return networks

    def connect(self, network: str, password: str=''):
        # TODO: Would break if name contained "
        os.system('/usr/sbin/networksetup -setairportnetwork en1 "{network}" "{password}"'.format(network=network,
                                                                                                  password=password))

    def password(self, network: str):
        os.system('/usr/bin/security find-generic-password -wga "{network}"'.format(network=network))


wifi = WiFi()

if args.verb == 'on':
    wifi.power(True)
elif args.verb == 'off':
    wifi.power(False)
elif args.verb == 'list':
    for network in wifi.networks():
       print('{ssid} | {security}'.format(ssid=network['ssid'], security=network['security']))
elif args.verb == 'connect':
    network = args.network
    if not network:
        options = wifi.networks()
        # TODO: Clean up this line when it isn't midnight
        network = options[pick(['{ssid} | {security}'.format(ssid=network['ssid'], security=network['security']) for network in options], title='Choose a network:')[1]]['ssid']
    # TODO: Automatically recognize passwordless networks
    password = args.password
    if not password:
        password = networks.get(network)
    if not password:
        password = getpass()
    networks[network] = password
    with open(DATA_PATH, 'w') as f:
        json.dump(networks, f)
    wifi.connect(network, password)
elif args.verb == 'password':
    if networks.get(args.network):
        print(networks[args.network])
    else:
        wifi.password(args.network)
