#!/usr/bin/env python3

import argparse
import os
import json
from getpass import getpass

DATA_PATH = os.path.expanduser('~') + '/.wifdata'

parser = argparse.ArgumentParser(description='Handle internet connections on MacOS.')
parser.add_argument('verb')
parser.add_argument('-n', dest='network', help='Name of network to which to connect')
parser.add_argument('-p', dest='password', help='Password for network to which you wish to connect. USE NOT RECOMMENDED.')
args = parser.parse_args()

networks = {}
if os.path.isfile(DATA_PATH):
    with open(DATA_PATH, 'r') as f:
        networks = json.load(f)

if args.verb == 'on':
    # TODO: Detect proper interface, not always en1
    os.system('networksetup -setairportpower en1 on')
elif args.verb == 'off':
    os.system('networksetup -setairportpower en1 off')
# TODO: LIST
elif args.verb == 'connect':
    password = args.password
    if not password:
        password = networks.get(args.network)
    if not password:
        password = getpass()
    networks[args.network] = password
    with open(DATA_PATH, 'w') as f:
        json.dump(networks, f)
    # TODO: Do things in the background/more nicely
    os.system('networksetup -setairportnetwork en1 {network} {password}'.format(network=args.network,
                                                                                    password=password))

# TODO: get password
